name: RSS Update

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: pip install feedparser requests beautifulsoup4

    - run: python generate.py

    - name: Commit update
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "auto update" || exit 0
        git push
